apiVersion: v1
kind: Service
metadata:
  name: mysql 
  labels:
    app: mtc 
spec:
  sessionAffinity: ClientIP
  ports:
    - port: 3306 
      targetPort: 3306 
  selector:
    app: mtc 
    tier: mysql 
  type: NodePort

---
apiVersion: v1
kind: Service
metadata:
  name: wordpress-mysql
  labels:
    app: wordpress
spec:
  ports:
    - port: 3306
  selector:
    app: wordpress
    tier: mysql
  clusterIP: None
