apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: xenforo
  labels:
    app: mtc
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mtc
        tier: xenforo
    spec:
      containers:
      - image: jefflaplante/mtc_app
        name: xenforo
        resources:
          limits:
            cpu: 500m
            memory: 200Mi
        env:
        - name: DB_HOST
          value: mysql
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-pass
              key: password.txt
        ports:
        - containerPort: 9000
          name: xenforo
        volumeMounts:
        - name: persistent-storage
          mountPath: /var/www/html
      volumes:
      - name: persistent-storage
        persistentVolumeClaim:
          claimName: mtc-data
