apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nginx
  labels:
    app: mtc
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mtc
        tier: nginx
    spec:
      containers:
      - image: jefflaplante/nginx
        imagePullPolicy: Always
        name: nginx
        ports:
        - containerPort: 80
          name: nginx
        resources:
          limits:
            cpu: 200m
            memory: 100Mi
        volumeMounts:
        - name: persistent-storage
          mountPath: /var/www/html
          readOnly: true
        - name: mtc-nginx
          mountPath: /etc/nginx/conf.d/default.conf
          subPath: default.conf
      volumes:
      - name: persistent-storage
        persistentVolumeClaim:
          claimName: mtc-data
      - name: mtc-nginx
        configMap:
          name: mtc-nginx
