apiVersion: v1
kind: Service
metadata:
  labels:
    app: mtc
  name: nginx
  namespace: default
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: mtc
    tier: nginx
  sessionAffinity: None
  type: ClusterIP
