---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: gluster-pv-0
  labels:
    type: gluster
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  glusterfs:
    endpoints: glusterfs-cluster
    path: gv0 
    readOnly: false
  persistentVolumeReclaimPolicy: Retain
