apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mtc_data 
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  selector:
    matchLabels:
      type: "gluster"
