apiVersion: v1
kind: Service
metadata:
  labels:
    app: mtc
  name: varnish
  namespace: default
spec:
  ports:
  - port: 6081
    protocol: TCP
    targetPort: 6081
  selector:
    app: mtc
    tier: varnish
  sessionAffinity: None
  type: ClusterIP
